[package]
name = "roketo"
version = "1.0.0"
authors = ["Alex Kouprin <hello@kikimora.tech>"]
edition = "2021"

[dev-dependencies]
near-contract-standards = "=4.0.0-pre.9"
near-sdk = "=4.0.0-pre.9"
near-sdk-sim = "=4.0.0-pre.9"

anyhow = "1.0"
borsh = "0.9"
maplit = "1.0"
near-units = "0.2.0"
# arbitrary_precision enabled for u128 types that workspaces requires for Balance types
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
tokio = { version = "1.18.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
workspaces = "0.2.1"
pkg-config = "0.3.1"

finance = { path = "./finance" }
streaming = { path = "./streaming" }
locked-token = { path = "./locked_token" }
roke-token = { path = "./roke_token" }
nft-roketo = { path = "./examples/nft" }

[profile.release]
codegen-units=1
# Tell `rustc` to optimize for small code size
opt-level = "s"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
members = [
    "examples/nft",
    "finance",
    "streaming",
    "roke_token",
    "locked_token",
]