[package]
name = "roke-token"
version = "1.0.0"
authors = ["Alex Kouprin <hello@kikimora.tech>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common/" }
near-contract-standards = "=4.0.0-pre.9"
near-sdk = "=4.0.0-pre.9"
