[package]
name = "streaming"
version = "0.1.0"
authors = ["Alex Kouprin <hello@kikimora.tech>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-contract-standards = "=4.0.0-pre.8"
near-sdk = { version = "=4.0.0-pre.8", features = ["unstable"] }
