[package]
name = "tests-workspaces"
version = "0.0.0"
authors = ["Pavel Iakushin <piakushin@roke.to>"]
edition = "2021"

[dependencies]
tokio = { version = "1.23", features = ["macros", "rt"] }
futures = "0.3"
anyhow = "1.0"
workspaces = "0.7"
env_logger = "0.10"
log = "0.4"
near-sdk = "4.1"